# Generated by Django 4.2.2 on 2023-11-13 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Группа вопросов',
                'verbose_name_plural': 'Группы вопросов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Тип сертификации',
                'verbose_name_plural': 'Типы сертификации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Тип отгрузки',
                'verbose_name_plural': 'Типы отгрузки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Тип лицензии',
                'verbose_name_plural': 'Типы лицензий',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Тип продукта',
                'verbose_name_plural': 'Типы продуктов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeReliase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Тип реализации',
                'verbose_name_plural': 'Типы реализации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Тип статуса',
                'verbose_name_plural': 'Типы статусов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=50, null=True, verbose_name='Наименование')),
                ('status', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Статус')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Срок действия партнерского статуса')),
                ('requirement', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Требования к партнерскому статусу')),
                ('discount', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Вендор',
                'verbose_name_plural': 'Вендоры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='ФИО')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Срок действия сертификатов специалистов')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.vendor', verbose_name='У какого вендора?')),
            ],
            options={
                'verbose_name': 'Сертифицированный специалист',
                'verbose_name_plural': 'Сертифицированные специалисты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='vendor_price', verbose_name='Файл прайса')),
                ('date', models.DateField(blank=True, default='', null=True, verbose_name='Дата начала действия прайса')),
                ('vendor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.vendor')),
            ],
            options={
                'verbose_name': 'Прайс',
                'verbose_name_plural': 'Прайсы',
                'ordering': ['vendor'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatar_path')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('group', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.groupfaq')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['name', 'group'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('top_certified', models.BooleanField(default=False, null=True)),
                ('brif_description', models.TextField(default='', max_length=150, null=True)),
                ('whom_and_what_for', models.TextField(default='', max_length=150, null=True)),
                ('gen_form', models.FileField(default=None, null=True, upload_to='')),
                ('ship_kit', models.CharField(default='', max_length=200, null=True)),
                ('tech_support', models.CharField(default='', max_length=200, null=True)),
                ('owner_type', models.CharField(default='', max_length=100, null=True)),
                ('competitions', models.FileField(default=None, null=True, upload_to='')),
                ('license_brif', models.CharField(default='', max_length=200, null=True)),
                ('license_date', models.DateField(blank=True, null=True, verbose_name='Дата актуализации лицензии')),
                ('get_brif', models.CharField(default='', max_length=200, null=True)),
                ('analogs', models.CharField(default='', max_length=50, null=True)),
                ('battle_card', models.FileField(default=None, null=True, upload_to='')),
                ('price', models.FileField(default=None, null=True, upload_to='')),
                ('tz_descriptions', models.FileField(default=None, null=True, upload_to='')),
                ('tz_44fzs', models.FileField(default=None, null=True, upload_to='')),
                ('tz_dates', models.DateField(default='', null=True)),
                ('pilot_quests', models.FileField(default=None, null=True, upload_to='')),
                ('pilot_pmis', models.FileField(default=None, null=True, upload_to='')),
                ('pilot_descriptions', models.FileField(default=None, null=True, upload_to='')),
                ('pilot_plans', models.FileField(default=None, null=True, upload_to='')),
                ('pilot_diss', models.CharField(default='', max_length=50, null=True)),
                ('reg_axofts', models.FileField(default=None, null=True, upload_to='')),
                ('reg_quest_register_deals', models.FileField(default=None, null=True, upload_to='')),
                ('reg_reward_schemes', models.TextField(default='', max_length=50, null=True)),
                ('extra_comments', models.TextField(default='', null=True)),
                ('brochures', models.FileField(default=None, null=True, upload_to='')),
                ('presentation_products', models.FileField(default=None, null=True, upload_to='')),
                ('webinars', models.CharField(default='', max_length=50, null=True)),
                ('presentations', models.CharField(default='', max_length=50, null=True)),
                ('partner_webinars', models.CharField(default='', max_length=50, null=True)),
                ('product_type', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.typeproduct')),
                ('type_get', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.typeget')),
                ('type_license', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.typelicense')),
                ('vendor', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='ФИО')),
                ('phone_number', models.CharField(default='', max_length=50, verbose_name='Номер телефона')),
                ('email', models.CharField(default='', max_length=50, verbose_name='Адрес электронной почты')),
                ('product', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.product', verbose_name='Продукт')),
                ('vendor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.vendor', verbose_name='Вендор')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.questionfaq')),
            ],
            options={
                'verbose_name': 'Инструкция',
                'verbose_name_plural': 'Инструкции',
                'ordering': ['question', 'description'],
            },
        ),
    ]
