# Generated by Django 4.2.2 on 2023-11-20 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cert_brif',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type_cert',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.typecertification'),
        ),
    ]
