# Generated by Django 4.2.2 on 2023-06-22 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpartner',
            name='Срок действия статуса',
            field=models.DateField(default=datetime.datetime(2023, 6, 22, 18, 23, 0, 472395), max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorpartnerspecialist',
            name='Срок действия сертификата',
            field=models.DateField(default=datetime.datetime(2023, 6, 22, 18, 23, 0, 472395), max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorprices',
            name='Дата начала действия прайса',
            field=models.DateField(default=datetime.datetime(2023, 6, 22, 18, 23, 0, 472395)),
        ),
    ]
