# Generated by Django 4.2.2 on 2023-11-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0002_product_cert_brif_product_type_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reg_partnership_status',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
