# Generated by Django 4.2.2 on 2023-06-22 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0002_alter_vendorpartner_срок_действия_статуса_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id Блока <Внутренние материалы>',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='id Блока <Как проводить пилот>',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='id Блока <Материалы от Вендора>',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='id Блока <Регистрация сделок>',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='id Блока <Техническое задание>',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='Аналоги',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='Контактное лицо партнера>',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorpartner',
            name='Срок действия статуса',
            field=models.DateField(default=datetime.datetime(2023, 6, 22, 22, 45, 55, 56115), max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorpartnerspecialist',
            name='Срок действия сертификата',
            field=models.DateField(default=datetime.datetime(2023, 6, 22, 22, 45, 55, 56115), max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorprices',
            name='Дата начала действия прайса',
            field=models.DateField(default=datetime.datetime(2023, 6, 22, 22, 45, 55, 56115)),
        ),
    ]
