# Generated by Django 4.2.2 on 2023-06-23 05:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0003_product_id_блока_внутренние_материалы__and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id Блока <Варианты отгрузки>',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id Блока <Внутренние материалы>',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id Блока <Как проводить пилот>',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id Блока <Лицензирование>',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id Блока <Материалы от Вендора>',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id Блока <Реализация>',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id Блока <Регистрация сделок>',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id Блока <Сертификация>',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id Блока <Техническое задание>',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Дополнительный комментарий',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Прайс',
        ),
        migrations.AlterField(
            model_name='vendorpartner',
            name='Срок действия статуса',
            field=models.DateField(default=datetime.datetime(2023, 6, 23, 10, 39, 36, 605439), max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorpartnerspecialist',
            name='Срок действия сертификата',
            field=models.DateField(default=datetime.datetime(2023, 6, 23, 10, 39, 36, 605439), max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorprices',
            name='Дата начала действия прайса',
            field=models.DateField(default=datetime.datetime(2023, 6, 23, 10, 39, 36, 605439)),
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Наименование', models.CharField(default='', max_length=50)),
                ('id Продукта', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='KnowledgeBase.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Наименование', models.CharField(default='', max_length=50)),
                ('Описание', models.TextField(default='')),
                ('Прайсы', models.FileField(default=None, upload_to='')),
                ('id Продукта', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='KnowledgeBase.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Наименование', models.CharField(default='', max_length=50)),
                ('Описание', models.TextField(default='')),
                ('Дата начала действия лицензии', models.DateField(default=datetime.datetime(2023, 6, 23, 10, 39, 36, 605439))),
                ('id Продукта', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='KnowledgeBase.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfoDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Перечень характеристик', models.FileField(default=None, upload_to='')),
                ('ТЗ по 44-ФЗ', models.FileField(default=None, upload_to='')),
                ('Дата начала действия лицензии', models.DateField(default=datetime.datetime(2023, 6, 23, 10, 39, 36, 605439))),
                ('Панкета по пилоту', models.FileField(default=None, upload_to='')),
                ('ПМИ', models.FileField(default=None, upload_to='')),
                ('Дистрибутив', models.CharField(default='', max_length=50)),
                ('Описание блока <Как проведения пилота>', models.FileField(default=None, upload_to='')),
                ('План пилота блока <Для проведения пилота>', models.FileField(default=None, upload_to='')),
                ('Продажа через Axoft', models.FileField(default=None, upload_to='')),
                ('Анкета регестрации сделок', models.FileField(default=None, upload_to='')),
                ('Статус Вендора', models.FileField(default=None, upload_to='')),
                ('Схема вознаграждения', models.TextField(default='', max_length=50)),
                ('Дополнительный комментарий', models.TextField(default='')),
                ('id Продукта', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='KnowledgeBase.product')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Брошюра с официального статуса', models.FileField(default=None, upload_to='')),
                ('Презентация продукта', models.FileField(default=None, upload_to='')),
                ('Вебинар по продукту', models.CharField(default='', max_length=50)),
                ('Презентация', models.CharField(default='', max_length=50)),
                ('Закрытый вебинар для партнера', models.CharField(default='', max_length=50)),
                ('id Продукта', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='KnowledgeBase.product')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Наименование', models.CharField(default='', max_length=50)),
                ('Описание', models.TextField(default='')),
                ('id Продукта', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='KnowledgeBase.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ФИО', models.CharField(default='', max_length=50)),
                ('Номер телефона', models.CharField(default='', max_length=50)),
                ('Электронная почта', models.CharField(default='', max_length=50)),
                ('Месенджер', models.CharField(default='', max_length=20)),
                ('id Продукта', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='KnowledgeBase.product')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Наименование', models.CharField(default='', max_length=50)),
                ('Дата начала действия лицензии', models.DateField(default=datetime.datetime(2023, 6, 23, 10, 39, 36, 605439))),
                ('Файлы', models.FileField(default=None, upload_to='')),
                ('id Продукта', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='KnowledgeBase.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
