# Generated by Django 4.2.2 on 2023-11-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0003_product_reg_partnership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact_price',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
