# Generated by Django 4.2.2 on 2023-06-23 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0004_remove_product_id_блока_варианты_отгрузки__and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='Дата начала действия лицензии',
            field=models.DateField(default=datetime.datetime(2023, 6, 23, 10, 53, 4, 64976)),
        ),
        migrations.AlterField(
            model_name='infodeal',
            name='Дата начала действия лицензии',
            field=models.DateField(default=datetime.datetime(2023, 6, 23, 10, 53, 4, 64976)),
        ),
        migrations.AlterField(
            model_name='licence',
            name='Дата начала действия лицензии',
            field=models.DateField(default=datetime.datetime(2023, 6, 23, 10, 53, 4, 64976)),
        ),
        migrations.AlterField(
            model_name='vendorpartner',
            name='Срок действия статуса',
            field=models.DateField(default=datetime.datetime(2023, 6, 23, 10, 53, 4, 64976), max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorpartnerspecialist',
            name='Срок действия сертификата',
            field=models.DateField(default=datetime.datetime(2023, 6, 23, 10, 53, 4, 64976), max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorprices',
            name='Дата начала действия прайса',
            field=models.DateField(default=datetime.datetime(2023, 6, 23, 10, 53, 4, 64976)),
        ),
    ]
