# Generated by Django 4.2.2 on 2023-11-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0005_remove_product_license_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tz_dates',
        ),
    ]
