# Generated by Django 4.2.2 on 2023-11-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0006_remove_product_tz_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact_product',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
