# Generated by Django 4.2.2 on 2023-11-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0007_product_contact_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='extra_comments',
            new_name='extra_comments1',
        ),
        migrations.AddField(
            model_name='product',
            name='extra_comments2',
            field=models.TextField(default='', null=True),
        ),
    ]
