# Generated by Django 4.2.2 on 2023-12-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0008_rename_extra_comments_product_extra_comments1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fsb_certified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fsteck_certified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
