# Generated by Django 4.2.2 on 2023-12-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0009_product_fsb_certified_product_fsteck_certified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='competitions',
            field=models.FileField(default=None, null=True, upload_to='vendor_price'),
        ),
    ]
