# Generated by Django 4.2.2 on 2023-12-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0010_alter_product_competitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brochures',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='presentation_products',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
