# Generated by Django 4.2.2 on 2023-12-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0011_alter_product_brochures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brochures',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='presentation_products',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='presentations',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
