# Generated by Django 4.2.2 on 2023-12-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0012_alter_product_brochures_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='contact_product',
        ),
        migrations.AlterField(
            model_name='product',
            name='pilot_descriptions',
            field=models.TextField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reg_partnership_status',
            field=models.TextField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tech_support',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
