# Generated by Django 4.2.2 on 2023-12-12 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0013_remove_product_contact_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reliz_brif',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type_reliz',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.typereliase'),
        ),
    ]
