# Generated by Django 4.2.2 on 2023-12-12 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0014_product_reliz_brif_product_type_reliz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='cert_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='license_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
