# Generated by Django 4.2.2 on 2023-12-13 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0015_remove_product_price_product_cert_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reg_partnership_status',
        ),
        migrations.AddField(
            model_name='product',
            name='tz_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
