# Generated by Django 4.2.2 on 2023-12-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0016_remove_product_reg_partnership_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='presentations',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
