# Generated by Django 4.2.2 on 2023-12-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0017_alter_product_presentations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pilot_descriptions',
            field=models.TextField(default='', max_length=500, null=True),
        ),
    ]
