# Generated by Django 4.2.2 on 2023-07-11 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0019_rename_дата_начала_действия_лицензии_certification_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название группы вопросов', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Описание вопроса', models.CharField(default='', max_length=100)),
                ('id Группы вопросов', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='KnowledgeBase.group')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Описание решения', models.TextField(default='')),
                ('Вложения', models.FileField(default=None, upload_to='')),
                ('id Вопроса', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='KnowledgeBase.group')),
            ],
        ),
    ]
