# Generated by Django 4.2.2 on 2023-07-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0021_guide_status_guide_type_certification_guide_type_get_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='partners',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='prices',
        ),
        migrations.AddField(
            model_name='vendorpartner',
            name='discount',
            field=models.CharField(default='', max_length=50),
        ),
    ]
