# Generated by Django 4.2.2 on 2023-07-13 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0022_remove_vendor_contacts_remove_vendor_partners_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='extrainfo',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='infodeal',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='vendorpartner',
            old_name='vendor_id',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='vendorpartnerspecialist',
            old_name='vendor_partner_id',
            new_name='vendor_partner',
        ),
    ]
