# Generated by Django 4.2.2 on 2023-07-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0023_rename_product_id_contact_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorpartner',
            name='specialist_list',
        ),
    ]
