# Generated by Django 4.2.2 on 2023-07-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0025_alter_product_brif_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='analogs',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='battle_card',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='competencies',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='contact_face',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
