# Generated by Django 4.2.2 on 2023-07-14 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0026_alter_product_analogs_alter_product_battle_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id Вендора',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='KnowledgeBase.vendor'),
        ),
    ]
