# Generated by Django 4.2.2 on 2023-07-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0028_alter_contact_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='product',
            new_name='vendor',
        ),
    ]
