# Generated by Django 4.2.2 on 2023-07-14 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0029_rename_product_contact_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='period',
            field=models.DateField(default=django.utils.timezone.now, max_length=50),
        ),
    ]
