# Generated by Django 4.2.2 on 2023-07-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0030_contact_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='KnowledgeBase.product'),
        ),
    ]
