# Generated by Django 4.2.2 on 2023-07-14 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0032_alter_contact_product_alter_contact_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='product',
            field=models.ForeignKey(default=' ', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='KnowledgeBase.product'),
        ),
    ]
