# Generated by Django 4.2.2 on 2023-07-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0033_alter_contact_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id Вендора',
            new_name='vendor',
        ),
    ]
