# Generated by Django 4.2.2 on 2023-09-02 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0036_rename_vendor_partner_vendorpartnerspecialist_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpartnerspecialist',
            name='vendor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='KnowledgeBase.vendor'),
        ),
    ]
