# Generated by Django 4.2.2 on 2023-09-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0037_alter_vendorpartnerspecialist_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprices',
            old_name='id Вендора',
            new_name='vendor',
        ),
    ]
