# Generated by Django 4.2.2 on 2023-09-03 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0038_rename_id_вендора_vendorprices_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpartner',
            name='discount',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpartner',
            name='period',
            field=models.DateField(default=django.utils.timezone.now, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpartner',
            name='requirement',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpartner',
            name='status',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
