# Generated by Django 4.2.2 on 2023-09-03 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0039_alter_vendorpartner_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpartnerspecialist',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpartnerspecialist',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vendorpartnerspecialist',
            name='name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
