# Generated by Django 4.2.2 on 2023-09-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0040_alter_vendorpartnerspecialist_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
