# Generated by Django 4.2.2 on 2023-09-06 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0041_alter_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpartner',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KnowledgeBase.vendor'),
        ),
    ]
