# Generated by Django 4.2.2 on 2023-09-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0042_alter_vendorpartner_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='id Продукта',
        ),
        migrations.RemoveField(
            model_name='extrainfo',
            name='product',
        ),
        migrations.RemoveField(
            model_name='infodeal',
            name='product',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='id Продукта',
        ),
        migrations.RemoveField(
            model_name='price',
            name='id Продукта',
        ),
        migrations.RemoveField(
            model_name='realisation',
            name='id Продукта',
        ),
        migrations.RemoveField(
            model_name='vendorpartner',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendorpartnerspecialist',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendorprices',
            name='vendor',
        ),
        migrations.AddField(
            model_name='vendor',
            name='partner',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='KnowledgeBase.vendorpartner'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='prices',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='KnowledgeBase.vendorprices'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='specialist',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='KnowledgeBase.vendorpartnerspecialist'),
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='ExtraInfo',
        ),
        migrations.DeleteModel(
            name='InfoDeal',
        ),
        migrations.DeleteModel(
            name='Licence',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Realisation',
        ),
    ]
