# Generated by Django 4.2.2 on 2023-09-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0043_remove_department_id_продукта_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
