# Generated by Django 4.2.2 on 2023-09-08 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0044_alter_vendor_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='specialist',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='KnowledgeBase.vendorpartnerspecialist'),
        ),
    ]
