# Generated by Django 4.2.2 on 2023-09-08 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0045_alter_vendor_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='partner',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.vendorpartner'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='prices',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.vendorprices'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='specialist',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.vendorpartnerspecialist'),
        ),
    ]
