# Generated by Django 4.2.2 on 2023-09-08 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0046_alter_vendor_partner_alter_vendor_prices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='specialist',
        ),
        migrations.AddField(
            model_name='vendorpartnerspecialist',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.vendor'),
            preserve_default=False,
        ),
    ]
