# Generated by Django 4.2.2 on 2023-09-08 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0047_remove_vendor_specialist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='prices',
        ),
        migrations.AddField(
            model_name='vendor',
            name='discount',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='period',
            field=models.DateField(default=django.utils.timezone.now, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='requirement',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='VendorPartner',
        ),
    ]
