# Generated by Django 4.2.2 on 2023-09-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0048_remove_vendor_partner_remove_vendor_prices_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendorPartnerSpecialist',
            new_name='VendorSpecialist',
        ),
    ]
