# Generated by Django 4.2.2 on 2023-09-08 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0049_rename_vendorpartnerspecialist_vendorspecialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprices',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.vendor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='product',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='KnowledgeBase.product'),
        ),
    ]
