# Generated by Django 4.2.2 on 2023-09-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0050_vendorprices_vendor_alter_contact_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='GroupFAQ',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionFAQ',
        ),
    ]
