# Generated by Django 4.2.2 on 2023-09-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0051_rename_group_groupfaq_rename_question_questionfaq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Описание решения',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='Вложения',
            new_name='files',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='id Вопроса',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='groupfaq',
            old_name='Название группы вопросов',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='questionfaq',
            old_name='id Группы вопросов',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='questionfaq',
            old_name='Описание вопроса',
            new_name='name',
        ),
    ]
