# Generated by Django 4.2.2 on 2023-09-10 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0052_rename_описание_решения_answer_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='group',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='KnowledgeBase.questionfaq'),
        ),
    ]
