# Generated by Django 4.2.2 on 2023-09-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0053_remove_answer_group_answer_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guide_type_certification',
            new_name='TypeCertification',
        ),
        migrations.RenameModel(
            old_name='Guide_type_license',
            new_name='TypeGet',
        ),
        migrations.RenameModel(
            old_name='Guide_type_product',
            new_name='TypeLicense',
        ),
        migrations.RenameModel(
            old_name='Guide_type_reliase',
            new_name='TypeProduct',
        ),
        migrations.RenameModel(
            old_name='Guide_type_get',
            new_name='TypeReliase',
        ),
        migrations.RenameModel(
            old_name='Guide_status',
            new_name='TypeStatus',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='period',
        ),
        migrations.RemoveField(
            model_name='vendorprices',
            name='date',
        ),
        migrations.RemoveField(
            model_name='vendorspecialist',
            name='date',
        ),
    ]
