# Generated by Django 4.2.2 on 2023-09-12 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0055_remove_vendor_period_remove_vendorspecialist_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name'], 'verbose_name': 'Вендор', 'verbose_name_plural': 'Вендоры'},
        ),
        migrations.AlterModelOptions(
            name='vendorspecialist',
            options={'ordering': ['name'], 'verbose_name': 'Сертифицированный специалист', 'verbose_name_plural': 'Сертифицированные специалисты'},
        ),
        migrations.AlterField(
            model_name='vendor',
            name='discount',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(default=None, null=True, upload_to='', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=50, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='requirement',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Требования к партнерскому статусу'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vendorspecialist',
            name='name',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='vendorspecialist',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.vendor', verbose_name='У какого вендора?'),
        ),
    ]
