# Generated by Django 4.2.2 on 2023-09-12 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0056_alter_vendor_options_alter_vendorspecialist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='product',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.product'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='vendor',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.vendor'),
        ),
    ]
