# Generated by Django 4.2.2 on 2023-09-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0057_alter_contact_product_alter_contact_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorspecialist',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vendorspecialist',
            name='name',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='ФИО'),
        ),
    ]
