# Generated by Django 4.2.2 on 2023-09-13 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0058_vendorspecialist_date_alter_vendorspecialist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorspecialist',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 13)),
        ),
    ]
