# Generated by Django 4.2.2 on 2023-09-13 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0059_alter_vendorspecialist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorspecialist',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
