# Generated by Django 4.2.2 on 2023-09-18 14:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0061_alter_answer_question_alter_questionfaq_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='logo',
        ),
        migrations.AddField(
            model_name='vendor',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Срок действия партнерского статуса'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.vendor'),
        ),
    ]
