# Generated by Django 4.2.2 on 2023-09-18 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0062_remove_vendor_logo_vendor_date_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Срок действия партнерского статуса'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='discount',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='requirement',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Требования к партнерскому статусу'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
