# Generated by Django 4.2.2 on 2023-09-18 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0063_alter_vendor_date_alter_vendor_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorspecialist',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='vendorspecialist',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='ФИО'),
        ),
    ]
