# Generated by Django 4.2.2 on 2023-09-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0064_alter_vendorspecialist_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorspecialist',
            name='vendor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.vendor', verbose_name='У какого вендора?'),
        ),
    ]
