# Generated by Django 4.2.2 on 2023-09-19 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0066_alter_vendorspecialist_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'Контактное лицо', 'verbose_name_plural': 'Контактные лица'},
        ),
        migrations.AlterModelOptions(
            name='vendorprices',
            options={'ordering': ['vendor'], 'verbose_name': 'Прайс', 'verbose_name_plural': 'Прайсы'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='analogs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='battle_card',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brif_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='competencies',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gen_form',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ship_kit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tech_support',
        ),
        migrations.RemoveField(
            model_name='product',
            name='top',
        ),
        migrations.RemoveField(
            model_name='product',
            name='whom_and_what_for',
        ),
        migrations.RemoveField(
            model_name='vendorprices',
            name='price',
        ),
        migrations.AddField(
            model_name='vendorprices',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата начала действия прайса'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='', max_length=50, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='messanger',
            field=models.CharField(default='', max_length=20, verbose_name='Мессенджер'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='', max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='product',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='vendor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.vendor', verbose_name='Вендор'),
        ),
        migrations.AlterField(
            model_name='vendorprices',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='', verbose_name='Файл прайса'),
        ),
        migrations.AlterField(
            model_name='vendorprices',
            name='vendor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.vendor'),
        ),
        migrations.AlterField(
            model_name='vendorspecialist',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Срок действия сертификатов специалистов'),
        ),
    ]
