# Generated by Django 4.2.2 on 2023-09-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0067_alter_contact_options_alter_vendorprices_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question', 'description'], 'verbose_name': 'Инструкция', 'verbose_name_plural': 'Инструкции'},
        ),
        migrations.AlterModelOptions(
            name='groupfaq',
            options={'ordering': ['name'], 'verbose_name': 'Группа вопросов', 'verbose_name_plural': 'Группы вопросов'},
        ),
        migrations.AlterModelOptions(
            name='questionfaq',
            options={'ordering': ['name', 'group'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='typecertification',
            options={'ordering': ['name'], 'verbose_name': 'Тип сертификации', 'verbose_name_plural': 'Типы сертификации'},
        ),
        migrations.AlterModelOptions(
            name='typeget',
            options={'ordering': ['name'], 'verbose_name': 'Тип отгрузки', 'verbose_name_plural': 'Типы отгрузки'},
        ),
        migrations.AlterModelOptions(
            name='typelicense',
            options={'ordering': ['name'], 'verbose_name': 'Тип лицензии', 'verbose_name_plural': 'Типы лицензий'},
        ),
        migrations.AlterModelOptions(
            name='typeproduct',
            options={'ordering': ['name'], 'verbose_name': 'Тип продукта', 'verbose_name_plural': 'Типы продуктов'},
        ),
        migrations.AlterModelOptions(
            name='typereliase',
            options={'ordering': ['name'], 'verbose_name': 'Тип реализации', 'verbose_name_plural': 'Типы реализации'},
        ),
        migrations.AlterModelOptions(
            name='typestatus',
            options={'ordering': ['name'], 'verbose_name': 'Тип статуса', 'verbose_name_plural': 'Типы статусов'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='files',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
