# Generated by Django 4.2.2 on 2023-10-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0073_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='messanger',
        ),
    ]
