# Generated by Django 4.2.2 on 2023-10-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0074_remove_contact_messanger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprices',
            name='date',
            field=models.DateField(blank=True, default='', null=True, verbose_name='Дата начала действия прайса'),
        ),
        migrations.AlterField(
            model_name='vendorprices',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='vendor_price', verbose_name='Файл прайса'),
        ),
    ]
